spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/expense-event
    password: root
  jpa:
    database-platform=org: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
